---
language: node_js
node_js:
  - "8"
  - "10"
  - "node"

cache: yarn

install: yarn
script:
  - yarn test

after_script:
  - yarn add -D coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "10"
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
