---
version: "3.6"
services:
  node:
    env_file:
      - .env
    image: node:10.16.0-alpine
    volumes:
      - ./:/app
    working_dir:
      /app
    networks:
      - web

networks:
  web:
    external: true
